# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "444619ca3904f79f338f460150e1fd17"
name = "CookieScript"
handle = "cookiescript"
application_url = "https://camps-library-careful-visit.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cookiescript.myshopify.com"

[auth]
redirect_urls = [
  "https://camps-library-careful-visit.trycloudflare.com/auth/callback",
  "https://camps-library-careful-visit.trycloudflare.com/auth/shopify/callback",
  "https://camps-library-careful-visit.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-01"

[pos]
embedded = false
